# Generated by Django 4.0.5 on 2022-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dessert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
