# Generated by Django 4.0.5 on 2022-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_breakfast_product_dessert_product_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile/pix.jpg', upload_to='profile'),
        ),
    ]
