# Generated by Django 4.0.5 on 2022-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product/onion-rings-d1.jpg', upload_to='product'),
        ),
    ]
